# Generated by Django 6.1.1 on 2026-09-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0002_expiryitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiryitem',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
